sudo: false
language: python
dist: xenial
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6
cache: pip
env:
  global:
    - PYTHONWARNINGS=default,ignore::PendingDeprecationWarning,ignore::ResourceWarning
    - DJANGO_DATABASE_USER_POSTGRES=postgres
    - DJANGO_DATABASE_USER_MYSQL=travis
  matrix:
    - DJANGO='>=3.1,<3.2'
    - DJANGO='>=3.0,<3.1'
    - DJANGO='>=2.2,<3.0'
matrix:
  fast_finish: true
services:
  - docker
install:
  - pip install --pre django$DJANGO
  - pip install -r tests/requirements.txt
  - pip install -e .
before_script:
  - docker pull amazon/dynamodb-local
  - docker run -d -p 8000:8000 amazon/dynamodb-local:1.13.4
script:
  - flake8 --config .config/flake8 pydjamodb
  - coverage run tests/manage.py test tests
after_success:
  - coverage report
notifications:
  email: false
